apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-ds
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    uid: loki-ds
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo-ds
          matcherRegex: '"trace_id":"([0-9a-f]+)"'
          name: TraceID
          url: '$${__value.raw}'

  - name: Tempo
    uid: tempo-ds
    type: tempo
    access: proxy
    url: http://tempo:3200
